const ROLE_VALUES = Object.freeze({
  EMPLOYEE: 'employee',
  MANAGER: 'manager',
  SENIOR_MANAGER: 'senior-manager',
  HR: 'hr',
  ADMIN: 'admin',
  SUPER_ADMIN: 'super-admin',
  PROFILE: 'profile',
  USER: 'user',
  SYSTEM: 'system'
});

const ADMIN_ROLES = Object.freeze([ROLE_VALUES.ADMIN, ROLE_VALUES.SUPER_ADMIN]);
const ADMIN_SCOPE_ROLES = Object.freeze([ROLE_VALUES.ADMIN, ROLE_VALUES.SUPER_ADMIN, ROLE_VALUES.HR]);
const MANAGER_ROLES = Object.freeze([ROLE_VALUES.MANAGER, ROLE_VALUES.SENIOR_MANAGER]);
const MANAGER_SCOPE_ROLES = Object.freeze([
  ROLE_VALUES.MANAGER,
  ROLE_VALUES.SENIOR_MANAGER,
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMIN,
  ROLE_VALUES.HR
]);
const EXTENDED_MANAGER_SCOPE_ROLES = Object.freeze([
  ROLE_VALUES.SENIOR_MANAGER,
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMIN,
  ROLE_VALUES.HR
]);
const PRIVILEGED_ROLES = Object.freeze([ROLE_VALUES.ADMIN, ROLE_VALUES.SUPER_ADMIN, ROLE_VALUES.HR]);
const REVIEW_MANAGER_ROLES = Object.freeze([
  ROLE_VALUES.MANAGER,
  ROLE_VALUES.SENIOR_MANAGER,
  ROLE_VALUES.ADMIN,
  ROLE_VALUES.SUPER_ADMIN,
  ROLE_VALUES.HR
]);

module.exports = {
  ROLE_VALUES,
  ADMIN_ROLES,
  ADMIN_SCOPE_ROLES,
  MANAGER_ROLES,
  MANAGER_SCOPE_ROLES,
  EXTENDED_MANAGER_SCOPE_ROLES,
  PRIVILEGED_ROLES,
  REVIEW_MANAGER_ROLES
};